version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - 3000:80
    depends_on:
      - web

  web:
    build: ./app
    restart: always
    expose:
      - 3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: "mongo:4.4.6"
    restart: always
    env_file:
      - .env
    expose:
      - "${DATABASE_PORT}"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - mongo_data:/data/db

volumes:
  mongo_data:
